import {
  pgTable,
  serial,
  text,
  varchar,
  integer,
  real,
  jsonb,
  timestamp,
} from 'drizzle-orm/pg-core';

// ─── Presidents ─────────────────────────────────────────────
export const presidents = pgTable('presidents', {
  id: varchar('id', { length: 16 }).primaryKey(),
  name: text('name').notNull(),
  name_en: text('name_en'),
  term_start: varchar('term_start', { length: 10 }).notNull(),
  term_end: varchar('term_end', { length: 10 }),
  party: text('party'),
  era: text('era'),
  gdp_growth_avg: real('gdp_growth_avg'),
  portrait_url: text('portrait_url'),
  note: text('note'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

// ─── Fiscal Yearly ──────────────────────────────────────────
export const fiscalYearly = pgTable('fiscal_yearly', {
  id: serial('id').primaryKey(),
  year: integer('year').notNull(),
  total_spending: real('total_spending'),
  total_revenue: real('total_revenue'),
  tax_revenue: real('tax_revenue'),
  national_debt: real('national_debt'),
  gdp: real('gdp'),
  debt_to_gdp: real('debt_to_gdp'),
  fiscal_balance: real('fiscal_balance'),
  president_id: varchar('president_id', { length: 16 }).references(() => presidents.id),
  created_at: timestamp('created_at').defaultNow(),
});

// ─── Audit Flags ────────────────────────────────────────────
export const auditFlags = pgTable('audit_flags', {
  id: varchar('id', { length: 32 }).primaryKey(),
  pattern_type: varchar('pattern_type', { length: 64 }).notNull(),
  severity: varchar('severity', { length: 16 }).notNull(),
  suspicion_score: real('suspicion_score').notNull(),
  target_type: varchar('target_type', { length: 32 }),
  target_id: text('target_id'),
  detail: jsonb('detail'),
  evidence: jsonb('evidence'),
  ai_analysis: text('ai_analysis'),
  related_bai_case: text('related_bai_case'),
  status: varchar('status', { length: 32 }).notNull(),
  plain_explanation: text('plain_explanation'),
  why_it_matters: text('why_it_matters'),
  citizen_impact: text('citizen_impact'),
  what_should_happen: text('what_should_happen'),
  real_case_example: text('real_case_example'),
  related_links: jsonb('related_links'),
  contracts: jsonb('contracts'),
  timeline: jsonb('timeline'),
  // AI enrichment columns
  summary: text('summary'),
  target_institution: text('target_institution'),
  ai_headline: text('ai_headline'),
  ai_narrative: text('ai_narrative'),
  ai_questions: jsonb('ai_questions'),
  ai_risk_assessment: text('ai_risk_assessment'),
  ai_comparable: text('ai_comparable'),
  ai_enriched_at: timestamp('ai_enriched_at'),
  ai_model: text('ai_model'),
  similar_cases: jsonb('similar_cases'),
  evidence_contracts: jsonb('evidence_contracts'),
  vendor_profile: jsonb('vendor_profile'),
  verdict: varchar('verdict', { length: 16 }),
  verdict_reason: text('verdict_reason'),
  key_evidence: text('key_evidence'),
  priority_tier: integer('priority_tier'),
  news_coverage: jsonb('news_coverage'),
  innocent_explanation: text('innocent_explanation'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

// ─── Bills ──────────────────────────────────────────────────
export const bills = pgTable('bills', {
  id: varchar('id', { length: 32 }).primaryKey(),
  bill_no: varchar('bill_no', { length: 32 }),
  title: text('title').notNull(),
  proposed_date: varchar('proposed_date', { length: 10 }),
  proposer_type: varchar('proposer_type', { length: 16 }),
  proposer_name: text('proposer_name'),
  committee: text('committee'),
  status: varchar('status', { length: 32 }),
  status_detail: text('status_detail'),
  vote_result: jsonb('vote_result'),
  ai_summary: text('ai_summary'),
  ai_category: varchar('ai_category', { length: 32 }),
  ai_controversy_score: real('ai_controversy_score'),
  ai_citizen_impact: text('ai_citizen_impact'),
  co_sponsors_count: integer('co_sponsors_count'),
  // Additional bill detail columns
  background: text('background'),
  problem_statement: text('problem_statement'),
  citizen_impact_detail: jsonb('citizen_impact_detail'),
  controversy_detail: jsonb('controversy_detail'),
  perspectives: jsonb('perspectives'),
  co_sponsors: jsonb('co_sponsors'),
  bill_timeline: jsonb('bill_timeline'),
  related_bills: jsonb('related_bills'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

// ─── News Events ────────────────────────────────────────────
export const newsEvents = pgTable('news_events', {
  id: varchar('id', { length: 32 }).primaryKey(),
  title: text('title').notNull(),
  event_date: varchar('event_date', { length: 10 }),
  category: varchar('category', { length: 32 }),
  ai_summary: text('ai_summary'),
  key_facts: jsonb('key_facts'),
  progressive_frame: jsonb('progressive_frame'),
  conservative_frame: jsonb('conservative_frame'),
  citizen_takeaway: text('citizen_takeaway'),
  article_count: integer('article_count'),
  coverage: jsonb('coverage'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

// ─── Legislators ────────────────────────────────────────────
export const legislators = pgTable('legislators', {
  id: varchar('id', { length: 32 }).primaryKey(),
  name: text('name').notNull(),
  name_en: text('name_en'),
  party: text('party'),
  district: text('district'),
  region: varchar('region', { length: 32 }),
  elected_count: integer('elected_count'),
  committee: text('committee'),
  attendance_rate: real('attendance_rate'),
  vote_participation_rate: real('vote_participation_rate'),
  pledge_fulfillment_rate: real('pledge_fulfillment_rate'),
  ai_activity_score: real('ai_activity_score'),
  consistency_score: real('consistency_score'),
  bills_proposed_count: integer('bills_proposed_count'),
  bills_passed_count: integer('bills_passed_count'),
  speech_count: integer('speech_count'),
  asset_total: real('asset_total'),
  age: integer('age'),
  gender: varchar('gender', { length: 4 }),
  career_summary: text('career_summary'),
  consistency_details: jsonb('consistency_details'),
  // Scoring and ranking columns
  recent_bills: jsonb('recent_bills'),
  photo_url: text('photo_url'),
  primary_area: text('primary_area'),
  bills_effective_rate: real('bills_effective_rate'),
  bipartisan_rate: real('bipartisan_rate'),
  bipartisan_bills: integer('bipartisan_bills'),
  spending_total: real('spending_total'),
  spending_self_promo_pct: real('spending_self_promo_pct'),
  words_vs_actions_score: real('words_vs_actions_score'),
  activity_score: real('activity_score'),
  rank_overall: integer('rank_overall'),
  grade: varchar('grade', { length: 4 }),
  bills_passage_rate: real('bills_passage_rate'),
  bills_week: integer('bills_week'),
  bills_month: integer('bills_month'),
  bills_quarter: integer('bills_quarter'),
  bills_year: integer('bills_year'),
  bills_pending: integer('bills_pending'),
  bills_partial: integer('bills_partial'),
  bills_effective: real('bills_effective'),
  policy_areas: jsonb('policy_areas'),
  bipartisan_parties: jsonb('bipartisan_parties'),
  stated_focus_areas: jsonb('stated_focus_areas'),
  actual_focus_areas: jsonb('actual_focus_areas'),
  consistency_items: jsonb('consistency_items'),
  assembly_id: text('assembly_id').unique(),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

// ─── Department Scores ──────────────────────────────────────
export const departmentScores = pgTable('department_scores', {
  id: serial('id').primaryKey(),
  department: text('department').notNull(),
  year: integer('year'),
  quarter: integer('quarter'),
  suspicion_score: real('suspicion_score').notNull(),
  flag_count: integer('flag_count').notNull(),
  transparency_rank: integer('transparency_rank'),
  details: jsonb('details'),
  created_at: timestamp('created_at').defaultNow(),
});

// ─── Data Sync Log ──────────────────────────────────────────
export const dataSyncLog = pgTable('data_sync_log', {
  id: serial('id').primaryKey(),
  source: varchar('source', { length: 32 }).notNull(),
  status: varchar('status', { length: 16 }).notNull(),
  records_fetched: integer('records_fetched'),
  records_updated: integer('records_updated'),
  started_at: timestamp('started_at'),
  completed_at: timestamp('completed_at'),
  error_message: text('error_message'),
});
